#pragma once

#define BLOCK_SIZE     32
#define BLOCK_SIZE_SQ  BLOCK_SIZE*BLOCK_SIZE
#define BLOCK_VOLUME   BLOCK_SIZE*BLOCK_SIZE*BLOCK_SIZE

#define SECTOR_WIDTH     16
#define SECTOR_WIDTH_SQ  SECTOR_WIDTH*SECTOR_WIDTH
#define SECTOR_HEIGHT    16


#define SECTOR_TIMES_BLOCK_SIZE    SECTOR_WIDTH*BLOCK_SIZE
#define SECTOR_TIMES_BLOCK_HEIGHT  SECTOR_HEIGHT*BLOCK_SIZE

#define WORLD_SEED 3